### ISSUE TITLE
numbers need commas

### ISSUE THREAD

**Issue by FingerCramp** [jexmarc/ctracker#9]
Your ctracker needs numbers with commas for easier readability.  Not sure how to do it in python or javascript, but here's my perl function:

> sub commify {
>    my $num = shift;
>    return $num if $num < 1000;
>    my $reversed = reverse $num;
>    $reversed =~ s/(\d\d\d)(?=\d)(?!\d*\.)/$1,/g;
>   return scalar reverse $reversed;
> }

**Comment by jexmarc** [comment]
This has been fixed. Added 2 new JS functions:

- commafy() Adds commas for displaying
- uncommafy() Removes commas to be done before calculations
